# Generated by Django 5.2.7
# ویرایش: وابستگی به access و فیلد group حذف شد (دسترسی استاندارد جنگو)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, null=True),
        ),
    ]
