# Generated by Django 5.2.7 on 2026-02-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending_activation', 'در انتظار تایید'), ('active', 'فعال'), ('suspended', 'مسدود شده')], max_length=18),
        ),
    ]
