# Generated by Django 5.2.7 on 2026-02-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='access',
            new_name='accounts_ac_name_736850_idx',
            old_name='accounts_acc_name_idx',
        ),
        migrations.RenameIndex(
            model_name='access',
            new_name='accounts_ac_parent__1b80bd_idx',
            old_name='accounts_acc_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='access',
            new_name='accounts_ac_is_menu_9d4363_idx',
            old_name='accounts_acc_ismenu_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='accounts_ac_name_558358_idx',
            old_name='accounts_act_name_idx',
        ),
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='accounts_ac_user_id_191351_idx',
            old_name='accounts_al_user_idx',
        ),
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='accounts_ac_action__d33543_idx',
            old_name='accounts_al_action_idx',
        ),
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='accounts_ac_created_5c8449_idx',
            old_name='accounts_al_created_idx',
        ),
        migrations.RenameIndex(
            model_name='group',
            new_name='accounts_gr_name_fde4c5_idx',
            old_name='accounts_gr_name_idx',
        ),
        migrations.RenameIndex(
            model_name='groupaccess',
            new_name='accounts_gr_group_i_640914_idx',
            old_name='accounts_ga_group_idx',
        ),
        migrations.RenameIndex(
            model_name='groupaccess',
            new_name='accounts_gr_access__253bb1_idx',
            old_name='accounts_ga_access_idx',
        ),
    ]
