# Generated by Django 5.2.7 on 2026-02-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='fname', max_length=255)),
                ('order_type', models.PositiveSmallIntegerField(db_column='forder_types', default=0)),
            ],
            options={
                'db_table': 'projects_projecttype',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='fname', max_length=255)),
                ('price', models.BigIntegerField(db_column='fprice', default=0)),
                ('deadline', models.DateField(blank=True, db_column='fdeadline', null=True)),
                ('progress', models.PositiveSmallIntegerField(db_column='fprogress', default=0)),
                ('priority', models.PositiveSmallIntegerField(db_column='fpriority', default=0)),
                ('customer', models.ForeignKey(db_column='fcustomer_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer')),
                ('project_type', models.ForeignKey(blank=True, db_column='fproject_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projecttype')),
            ],
            options={
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='CustomerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column='fcustomer_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='customers.customer')),
                ('project', models.ForeignKey(db_column='fproject_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='projects.project')),
            ],
            options={
                'db_table': 'projects_customerproject',
                'unique_together': {('project', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(db_column='fcontent_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='content.content')),
                ('project', models.ForeignKey(db_column='fproject_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='projects.project')),
            ],
            options={
                'db_table': 'projects_projectcontent',
                'unique_together': {('project', 'content')},
            },
        ),
    ]
