# Generated by Django 5.2.7 on 2026-02-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='order_type',
        ),
    ]
