# Generated by Django 5.2.7 on 2026-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='ftitle', max_length=255)),
                ('is_uploaded', models.BooleanField(db_column='fis_uploaded', default=False)),
                ('published_date', models.DateField(blank=True, db_column='fpublished_date', null=True)),
                ('tags', models.JSONField(blank=True, db_column='ftags', null=True)),
            ],
            options={
                'db_table': 'content_content',
            },
        ),
    ]
