# Generated by Django 5.2.7 on 2026-02-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='fname', max_length=255)),
                ('description', models.TextField(blank=True, db_column='fdescription')),
                ('deadline', models.DateField(blank=True, db_column='fdeadline', null=True)),
                ('priority', models.PositiveSmallIntegerField(db_column='fpriority', default=0)),
                ('estimate', models.PositiveSmallIntegerField(db_column='festimate', default=0)),
                ('assignee', models.ForeignKey(blank=True, db_column='fassignee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='fproject_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'db_table': 'tasks_task',
            },
        ),
        migrations.CreateModel(
            name='ContentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(db_column='fcontent_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='content.content')),
                ('task', models.ForeignKey(db_column='ftask_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_contenttask',
                'unique_together': {('content', 'task')},
            },
        ),
    ]
