# Generated by Django 5.2.7 on 2026-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='ffname', max_length=255)),
                ('last_name', models.CharField(db_column='flname', max_length=255)),
                ('number', models.CharField(db_column='fnumber', max_length=64)),
            ],
            options={
                'db_table': 'customers_customer',
            },
        ),
    ]
